"use client";
import { useEffect, useState } from "react";
import { Button } from "@heroui/react";
import { jsPDF } from "jspdf";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Building2, Download, Landmark, ReceiptText } from "lucide-react";
import { api } from "@/lib/api";
import { LoadingState } from "@/components/LoadingState";
export default function OwnerDashboardPage() {
    const [data, setData] = useState(null);
    useEffect(() => { api.get("/admin/owner/analytics").then(({ data }) => setData(data.data)).catch(() => setData({ totalEarnings: 0, totalProperties: 0, totalBookings: 0, monthlyEarnings: [] })); }, []);
    if (!data)
        return <LoadingState label="Preparing your analytics…"/>;
    const download = () => { const pdf = new jsPDF(); pdf.setFontSize(22); pdf.text("Nestora monthly earnings report", 18, 22); pdf.setFontSize(11); pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 18, 31); pdf.setFontSize(15); pdf.text(`Total earnings: $${data.totalEarnings.toLocaleString()}`, 18, 45); pdf.text(`Approved bookings: ${data.totalBookings}`, 18, 54); pdf.setFontSize(12); let y = 72; data.monthlyEarnings.forEach((item) => { pdf.text(`${item.month}: $${item.earnings.toLocaleString()}`, 22, y); y += 8; }); pdf.save("nestora-monthly-earnings.pdf"); };
    const cards = [{ label: "Total earnings", value: `$${data.totalEarnings.toLocaleString()}`, icon: Landmark, tone: "bg-amber-100 text-amber-900" }, { label: "Total properties", value: data.totalProperties, icon: Building2, tone: "bg-emerald-100 text-emerald-900" }, { label: "Confirmed bookings", value: data.totalBookings, icon: ReceiptText, tone: "bg-sky-100 text-sky-900" }];
    return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="section-kicker">Owner dashboard</span><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Your rental performance</h1><p className="mt-2 text-sm text-[var(--muted)]">A clear view of the bookings and revenue your properties are creating.</p></div><Button variant="flat" onPress={download}><Download size={17}/>Download report</Button></div><div className="mt-7 grid gap-4 md:grid-cols-3">{cards.map((card) => <article key={card.label} className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5"><div className={`grid size-10 place-items-center rounded-2xl ${card.tone}`}><card.icon size={20}/></div><p className="mt-5 text-3xl font-black">{card.value}</p><p className="mt-1 text-sm font-semibold text-[var(--muted)]">{card.label}</p></article>)}</div><section className="mt-6 rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 sm:p-6"><div><h2 className="text-xl font-black">Monthly earnings</h2><p className="mt-1 text-sm text-[var(--muted)]">Successful payments across the last twelve months.</p></div><div className="mt-6 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthlyEarnings} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="earningsGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#176b52" stopOpacity={.35}/><stop offset="95%" stopColor="#176b52" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--line)" vertical={false}/><XAxis dataKey="month" fontSize={12} tickLine={false} axisLine={false}/><YAxis fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`}/><Tooltip formatter={(value) => [`$${Number(value).toLocaleString()}`, "Earnings"]}/><Area type="monotone" dataKey="earnings" stroke="#176b52" strokeWidth={3} fill="url(#earningsGradient)"/></AreaChart></ResponsiveContainer></div></section></div>;
}
